# -*- mode: python -*-
a = Analysis(['LinguaCinema.py'],
             pathex=['../Lingualeo_player'],
             hiddenimports=[],
             hookspath=None)
a.datas += [
            ('bitmaps/player_next.png', '../Lingualeo_player/bitmaps/player_next.png',  'DATA'),
            ('bitmaps/player_play.png', '../Lingualeo_player/bitmaps/player_play.png',  'DATA'),
            ('bitmaps/player_prev.png', '../Lingualeo_player/bitmaps/player_prev.png',  'DATA'),
            ('bitmaps/player_stop.png', '../Lingualeo_player/bitmaps/player_stop.png',  'DATA'),
            ('bitmaps/player_pause.png', '../Lingualeo_player/bitmaps/player_pause.png',  'DATA'),
            ('bitmaps/player_replay.png', '../Lingualeo_player/bitmaps/player_replay.png',  'DATA'),
            ('bin/osx/mplayer', '../Lingualeo_player/bin/osx/mplayer',  'DATA'),
            ('bin/osx/lib/libSDL-1.2.0.dylib', '../Lingualeo_player/bin/osx/lib/libSDL-1.2.0.dylib',  'DATA'),
            ('bin/osx/lib/libass.4.dylib', '../Lingualeo_player/bin/osx/lib/libass.4.dylib',  'DATA'),
            ('bin/osx/lib/libavcodec.54.dylib', '../Lingualeo_player/bin/osx/lib/libavcodec.54.dylib',  'DATA'),
            ('bin/osx/lib/libavformat.54.dylib', '../Lingualeo_player/bin/osx/lib/libavformat.54.dylib',  'DATA'),
            ('bin/osx/lib/libavutil.52.dylib', '../Lingualeo_player/bin/osx/lib/libavutil.52.dylib',  'DATA'),
            ('bin/osx/lib/libbz2.1.0.dylib', '../Lingualeo_player/bin/osx/lib/libbz2.1.0.dylib',  'DATA'),
            ('bin/osx/lib/libcrypto.1.0.0.dylib', '../Lingualeo_player/bin/osx/lib/libcrypto.1.0.0.dylib',  'DATA'),
            ('bin/osx/lib/libcurl.4.dylib', '../Lingualeo_player/bin/osx/lib/libcurl.4.dylib',  'DATA'),
            ('bin/osx/lib/libdca.0.dylib', '../Lingualeo_player/bin/osx/lib/libdca.0.dylib',  'DATA'),
            ('bin/osx/lib/libdv.4.dylib', '../Lingualeo_player/bin/osx/lib/libdv.4.dylib',  'DATA'),
            ('bin/osx/lib/libdvdnavmini.4.dylib', '../Lingualeo_player/bin/osx/lib/libdvdnavmini.4.dylib',  'DATA'),
            ('bin/osx/lib/libdvdread.4.dylib', '../Lingualeo_player/bin/osx/lib/libdvdread.4.dylib',  'DATA'),
            ('bin/osx/lib/libenca.0.dylib', '../Lingualeo_player/bin/osx/lib/libenca.0.dylib',  'DATA'),
            ('bin/osx/lib/libexpat.1.dylib', '../Lingualeo_player/bin/osx/lib/libexpat.1.dylib',  'DATA'),
            ('bin/osx/lib/libfaad.2.dylib', '../Lingualeo_player/bin/osx/lib/libfaad.2.dylib',  'DATA'),
            ('bin/osx/lib/libfontconfig.1.dylib', '../Lingualeo_player/bin/osx/lib/libfontconfig.1.dylib',  'DATA'),
            ('bin/osx/lib/libfreetype.6.dylib', '../Lingualeo_player/bin/osx/lib/libfreetype.6.dylib',  'DATA'),
            ('bin/osx/lib/libfribidi.0.dylib', '../Lingualeo_player/bin/osx/lib/libfribidi.0.dylib',  'DATA'),
            ('bin/osx/lib/libiconv.2.dylib', '../Lingualeo_player/bin/osx/lib/libiconv.2.dylib',  'DATA'),
            ('bin/osx/lib/libidn.11.dylib', '../Lingualeo_player/bin/osx/lib/libidn.11.dylib',  'DATA'),
            ('bin/osx/lib/libintl.8.dylib', '../Lingualeo_player/bin/osx/lib/libintl.8.dylib',  'DATA'),
            ('bin/osx/lib/libjack.0.dylib', '../Lingualeo_player/bin/osx/lib/libjack.0.dylib',  'DATA'),
            ('bin/osx/lib/libjpeg.9.dylib', '../Lingualeo_player/bin/osx/lib/libjpeg.9.dylib',  'DATA'),
            ('bin/osx/lib/liblcms.1.dylib', '../Lingualeo_player/bin/osx/lib/liblcms.1.dylib',  'DATA'),
            ('bin/osx/lib/liblcms2.2.dylib', '../Lingualeo_player/bin/osx/lib/liblcms2.2.dylib',  'DATA'),
            ('bin/osx/lib/liblua.dylib', '../Lingualeo_player/bin/osx/lib/liblua.dylib',  'DATA'),
            ('bin/osx/lib/libmad.0.dylib', '../Lingualeo_player/bin/osx/lib/libmad.0.dylib',  'DATA'),
            ('bin/osx/lib/libmng.1.dylib', '../Lingualeo_player/bin/osx/lib/libmng.1.dylib',  'DATA'),
            ('bin/osx/lib/libmodplug.1.dylib', '../Lingualeo_player/bin/osx/lib/libmodplug.1.dylib',  'DATA'),
            ('bin/osx/lib/libmp3lame.0.dylib', '../Lingualeo_player/bin/osx/lib/libmp3lame.0.dylib',  'DATA'),
            ('bin/osx/lib/libncurses.5.dylib', '../Lingualeo_player/bin/osx/lib/libncurses.5.dylib',  'DATA'),
            ('bin/osx/lib/libogg.0.dylib', '../Lingualeo_player/bin/osx/lib/libogg.0.dylib',  'DATA'),
            ('bin/osx/lib/libopenjpeg.1.dylib', '../Lingualeo_player/bin/osx/lib/libopenjpeg.1.dylib',  'DATA'),
            ('bin/osx/lib/libopus.0.dylib', '../Lingualeo_player/bin/osx/lib/libopus.0.dylib',  'DATA'),
            ('bin/osx/lib/liborc-0.4.0.dylib', '../Lingualeo_player/bin/osx/lib/liborc-0.4.0.dylib',  'DATA'),
            ('bin/osx/lib/libpng15.15.dylib', '../Lingualeo_player/bin/osx/lib/libpng15.15.dylib',  'DATA'),
            ('bin/osx/lib/libpostproc.52.dylib', '../Lingualeo_player/bin/osx/lib/libpostproc.52.dylib',  'DATA'),
            ('bin/osx/lib/libquvi.7.dylib', '../Lingualeo_player/bin/osx/lib/libquvi.7.dylib',  'DATA'),
            ('bin/osx/lib/libschroedinger-1.0.0.dylib', '../Lingualeo_player/bin/osx/lib/libschroedinger-1.0.0.dylib'  ,  'DATA'),
            ('bin/osx/lib/libspeex.1.dylib', '../Lingualeo_player/bin/osx/lib/libspeex.1.dylib',  'DATA'),
            ('bin/osx/lib/libssl.1.0.0.dylib', '../Lingualeo_player/bin/osx/lib/libssl.1.0.0.dylib',  'DATA'),
            ('bin/osx/lib/libswscale.2.dylib', '../Lingualeo_player/bin/osx/lib/libswscale.2.dylib',  'DATA'),
            ('bin/osx/lib/libtheora.0.dylib', '../Lingualeo_player/bin/osx/lib/libtheora.0.dylib',  'DATA'),
            ('bin/osx/lib/libtheoradec.1.dylib', '../Lingualeo_player/bin/osx/lib/libtheoradec.1.dylib',  'DATA'),
            ('bin/osx/lib/libtheoraenc.1.dylib', '../Lingualeo_player/bin/osx/lib/libtheoraenc.1.dylib',  'DATA'),
            ('bin/osx/lib/libvorbis.0.dylib', '../Lingualeo_player/bin/osx/lib/libvorbis.0.dylib',  'DATA'),
            ('bin/osx/lib/libvorbisenc.2.dylib', '../Lingualeo_player/bin/osx/lib/libvorbisenc.2.dylib',  'DATA'),
            ('bin/osx/lib/libxvidcore.4.dylib', '../Lingualeo_player/bin/osx/lib/libxvidcore.4.dylib',  'DATA'),
            ('bin/osx/lib/libx264.129.dylib', '../Lingualeo_player/bin/osx/lib/libx264.129.dylib',  'DATA'),
            ('bin/osx/lib/libz.1.dylib', '../Lingualeo_player/bin/osx/lib/libz.1.dylib',  'DATA'),
            ('favicon.ico', '../Lingualeo_player/favicon.ico',  'DATA'),
            ('favicon.icns', '../Lingualeo_player/favicon.icns',  'DATA'),
#            ('bin/osx/mplayer/subfont.ttf', '../Lingualeo_player/bin/osx/mplayer/subfont.ttf',  'DATA'),
            ('bitmaps/flags/en.png', '../Lingualeo_player/bitmaps/flags/en.png',  'DATA'),
            ('bitmaps/flags/ru.png', '../Lingualeo_player/bitmaps/flags/ru.png',  'DATA'),
            ('bitmaps/flags/es.png', '../Lingualeo_player/bitmaps/flags/es.png',  'DATA'),
            ('bitmaps/flags/fr.png', '../Lingualeo_player/bitmaps/flags/fr.png',  'DATA'),
            ('bitmaps/flags/de.png', '../Lingualeo_player/bitmaps/flags/de.png',  'DATA'),
            ('bitmaps/flags/it.png', '../Lingualeo_player/bitmaps/flags/it.png',  'DATA'),
            ('bitmaps/flags/pt-pt.png', '../Lingualeo_player/bitmaps/flags/pt-pt.png',  'DATA'),
            ('bitmaps/flags/pt-br.png', '../Lingualeo_player/bitmaps/flags/pt-br.png',  'DATA'),
            ('bitmaps/flags/en.png', '../Lingualeo_player/bitmaps/flags/en.png',  'DATA'),
            ('bitmaps/flags/en.png', '../Lingualeo_player/bitmaps/flags/en.png',  'DATA'),
            ('locale/ru_RU/LC_MESSAGES/LinguaCinema.mo', '../Lingualeo_player/locale/ru_RU/LC_MESSAGES/LinguaCinema.mo',  'DATA'),
            ('locale/en_US/LC_MESSAGES/LinguaCinema.mo', '../Lingualeo_player/locale/en_US/LC_MESSAGES/LinguaCinema.mo',  'DATA'),
            ('locale/pt_BR/LC_MESSAGES/LinguaCinema.mo', '../Lingualeo_player/locale/pt_BR/LC_MESSAGES/LinguaCinema.mo',  'DATA'),
           ]
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=1,
          name=os.path.join('build/pyi.osx/LinguaCinema', 'LinguaCinema'),
          debug=False,
          strip=None,
          upx=True,
          icon="favicon.icns",
          console=False )

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=None,
               upx=True,
               name=os.path.join('dist', 'LinguaCinema.osx'))

app = BUNDLE(coll,
                 appname='LinguaCinema',
                 name=os.path.join('dist', 'LinguaCinema.app'),
                 icon="favicon.icns",
                 version=1)
