"""Subclass of LinguaFrame, which is generated by wxFormBuilder."""

import wx
import LinguaCinemaForms

# Implementing LinguaFrame
class LinguaCinemaLinguaFrame( LinguaCinemaForms.LinguaFrame ):
	def __init__( self, parent ):
		LinguaCinemaForms.LinguaFrame.__init__( self, parent )
	
